# Site settings
name: My Blog
email: hi.yuhang@outlook.com
author: Chase Huang
url: https://hy59.github.io/
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/hy59/
baseurl: ""
description: To love oneself is the beginning of a lifelong romance. 
meta_description: 黄禹;个人博客
motto: 千里之行，始于足下。
banner: 千里之行，始于足下。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Chase Huang

# Build settings
markdown: kramdown

baidu_analysis: 2998c8ba4e805c87ed41b3e037325e08

